---
version: "3"

services:
    iss-tracker-app:
        build:
            context: ./ 
            dockerfile: ./Dockerfile
        ports:
            - 5000:5000
        image: amandawlee/iss_tracker:midterm

